In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import neighbors, naive_bayes, tree, neural_network, linear_model
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
df = pd.read_csv("C:\\Users\\advai\\dsbda mini pro\\credit-card-default.csv")

In [3]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  defaulted  
0         0         0         0          1  
1      1000         0      2000          1  
2      1000      1000      5000          0  
3      1100      1069      1000          0  
4      9000       689       679          0  

[5 rows x 25 columns]

In [4]:
# data split
# Putting feature variable to X
X = df.drop('defaulted',axis=1)

# Putting response variable to y
y = df['defaulted']

# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [26]:
# K Neighbors Classifier
knc = neighbors.KNeighborsClassifier(n_neighbors=65,weights="uniform",p=2)
knc.fit(X_train,y_train)
knc_y_prid = knc.predict(X_test)
accuracy_score(y_test,knc_y_prid)

0.7828888888888889

In [65]:
print(classification_report(y_test,knc_y_prid))
print('\n')
print(confusion_matrix(y_test,knc_y_prid))

              precision    recall  f1-score   support

           0       0.79      0.98      0.88      7058
           1       0.47      0.06      0.10      1942

    accuracy                           0.78      9000
   macro avg       0.63      0.52      0.49      9000
weighted avg       0.72      0.78      0.71      9000



[[6939  119]
 [1835  107]]


In [43]:
# DecisionTreeClassifier
dtree = tree.DecisionTreeClassifier(min_samples_split=10,min_samples_leaf=100)
dtree.fit(X_train,y_train)
dtree_y_prid = dtree.predict(X_test)
accuracy_score(y_test,dtree_y_prid)

0.8248888888888889

In [66]:
print(classification_report(y_test,dtree_y_prid))
print('\n')
print(confusion_matrix(y_test,dtree_y_prid))

              precision    recall  f1-score   support

           0       0.84      0.95      0.90      7058
           1       0.68      0.36      0.47      1942

    accuracy                           0.82      9000
   macro avg       0.76      0.66      0.68      9000
weighted avg       0.81      0.82      0.80      9000



[[6724  334]
 [1242  700]]


In [49]:
# Ridge Classifier
rid_clf = linear_model.RidgeClassifier()
rid_clf.fit(X_train,y_train)
rid_clf_y_prid = rid_clf.predict(X_test)
accuracy_score(y_test,rid_clf_y_prid)

0.8062222222222222

In [67]:
print(classification_report(y_test,rid_clf_y_prid))
print('\n')
print(confusion_matrix(y_test,rid_clf_y_prid))

              precision    recall  f1-score   support

           0       0.81      0.99      0.89      7058
           1       0.76      0.15      0.25      1942

    accuracy                           0.81      9000
   macro avg       0.78      0.57      0.57      9000
weighted avg       0.80      0.81      0.75      9000



[[6964   94]
 [1650  292]]


In [57]:
# neural network
nn = neural_network.MLPClassifier(activation="relu",hidden_layer_sizes=(20,1),learning_rate_init=0.01 ,random_state=1)
nn.fit(X_train,y_train)
nn_y_prid = nn.predict(X_test)
accuracy_score(y_test,nn_y_prid)

0.7842222222222223

In [68]:
print(classification_report(y_test,nn_y_prid))
print('\n')
print(confusion_matrix(y_test,nn_y_prid))

              precision    recall  f1-score   support

           0       0.78      1.00      0.88      7058
           1       0.00      0.00      0.00      1942

    accuracy                           0.78      9000
   macro avg       0.39      0.50      0.44      9000
weighted avg       0.62      0.78      0.69      9000



[[7058    0]
 [1942    0]]


D:\asd\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\asd\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\asd\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
